### ISSUE TITLE
Specific CMake version?

### ISSUE THREAD

**Issue by ankarako** [mathstuf/cxx-modules-sandbox#34]
Hello, and thanks for this repo,

It is very helpful as c++20 modules are a very attractive feature of the latest standard.
In an effort to configure the project, cmake throws the following configuration error (on Windows):

 target_sources File set TYPE may only be "HEADERS"

So, I'd like to ask you if a need a specific cmake version for this to work (currently I am using version  3.23.1).

Thank you very much in advance!

**Comment by johan-boule** [comment]
IIRC Yes,
This git repository is bit unusually organised since it's "decomposed" into branches which have totally different content.
If you look at the "docker" branch, you will find a docker image which has patched toolsets (gcc, clang, cmake ...).
You can run this container to build the example code present on the master branch.

**Comment by ankarako** [comment]
Oh didn't notice. Thanks.
However, playing a little bit around with modules and CMAKE,  I realised that adding a static library targets, and naming modules with a .ixx extensions works like a charm, in MSVC at least.
